### ISSUE TITLE
Pre-Tutorial Google Form

### ISSUE THREAD

**Issue by alcantarar** [alcantarar/ASB_Tutorial#10]
Before the tutorial, we will send out an email to registered attendees with a google form. The primary goal is to better understand attendee's expectations and which programming language they use (since this tutorial is MATLAB-centric). Here are the questions (in rough form) I have so far, but please comment more below:

 1. What programming language will you be able to use during the tutorial?
    * MATLAB / Python / R / Other
1. What is your level of programming experience?
    * 0-1 yrs / 2-3 yrs / 4+ yrs
1. What are you most interested in using version control for?
    * Developing code / Writing manuscripts / I don't know what version control is used for / Other
1. What is your current level of knowledge of version control?
    * 1 (none) - 10 (I'm a pro and don't need to be taking a tutorial)

**Comment by alcantarar** [comment]
5. what operating system will you be using during the tutorial?
    * Windows/MacOS/Linux

**Comment by GBruening** [comment]
Need a survey to find group leaders. Should have three options for yes/maybe/no.
Also need to know what are their github usernames.

**Comment by alcantarar** [comment]
@GBruening @ross-wilkinson  what do you think about this survey? 

https://forms.gle/nkViZ9FYtBUCtAqp7

**Comment by ross-wilkinson** [comment]
I like everything that is in there. Two suggestions: 1) Could you add a 4th option of "None" for programming experience. I feel like 0-1 years covers a broad spectrum. My main thought for adding this is so that we can combine the programming experience and version control responses to get a good combination of people within each group. 2) I would be interested to know how each person's lab/team currently collaborates for writing code and manuscripts. So perhaps a question like "Please outline the processes/tools you currently use to share and work collaboratively on code and manuscript documents with your lab/team members. i.e. "We share documents via email." or "We write collaboratively using Overleaf."" (Provide room for short answer response).

**Comment by alcantarar** [comment]
Hopefully nobody says they have zero programming experience because programming experience is listed as a requirement in the tutorial description! I agree that we should balance out groups though. 

I've added the 4th option and the short answer for how people currently collaborate.

**Comment by ross-wilkinson** [comment]
Well, that's a very valid point Ryan.

**Comment by ross-wilkinson** [comment]
Looks good mate. I'll be interested to see the programming language split.

**Comment by GBruening** [comment]
I think we put in the tutorial either matlab or python, nothing about R.

Should probably remove R as an option.

**Comment by ross-wilkinson** [comment]
There is a chance that a larger portion of attendees use R than either MATLAB or Python. Not saying it's likely, but it seems like a good idea to check this beforehand. There is a package in R to convert the scripts _install.packages("matconv")_ if we need to.

**Comment by alcantarar** [comment]
Let's leave R in there. 

We can group attendees by language if needed based on the results from this survey. Converting this from matlab to python/R won't be difficult if there are users who can't use MATLAB. 

Alternatively, we just make sure one person in each group can run MATLAB and those who don't can edit the *.m files in a plain text editor. That's not the important part anyways.

**Comment by alcantarar** [comment]
Just sent out survey. closes this issue.
